version: 2.1

orbs:
  continuation: circleci/continuation@0.2.0
setup: true

parameters:
  run-workflow-a:
    type: boolean
    default: false 
  run-workflow-b:
    type: boolean
    default: false
  run-workflow-c:
    type: boolean
    default: false
  run-workflow-d:
    type: boolean
    default: false
  manual-workflow-a:
    type: boolean
    default: false 
  manual-workflow-b:
    type: boolean
    default: false
  manual-workflow-c:
    type: boolean
    default: false
  manual-workflow-d:
    type: boolean
    default: false
    

workflows:
  setup-b:
    when: 
      or: [<< pipeline.parameters.manual-workflow-b >>, << pipeline.parameters.run-workflow-b >>]
    jobs:
      - continuation/continue:
          configuration_path: dir_b/.circleci/workflows.yml
          parameters: /tmp/pipeline-parameters.json
          pre-steps:
            - run:
                command: |
                  echo '{ "run-workflow-b": << pipeline.parameters.manual-workflow-b >> }' >> /tmp/pipeline-parameters.json

  setup-a:
    when: 
      or: [<< pipeline.parameters.manual-workflow-a >>, << pipeline.parameters.run-workflow-a >>]
    jobs:
      - continuation/continue:
          configuration_path: dir_c/.circleci/workflows.yml
          parameters: /tmp/pipeline-parameters.json
          pre-steps:
            - run:
                command: |
                  echo '{ "run-workflow-a": << pipeline.parameters.manual-workflow-a >>}' >> /tmp/pipeline-parameters.json
  setup-c:
    when: 
      or: [<< pipeline.parameters.manual-workflow-c >>, << pipeline.parameters.run-workflow-c >>]
    jobs:
      - continuation/continue:
          configuration_path: dir_c/.circleci/workflows.yml
          parameters: /tmp/pipeline-parameters.json
          pre-steps:
            - run:
                command: |
                  echo '{ "run-workflow-c": << pipeline.parameters.manual-workflow-c >>}' >> /tmp/pipeline-parameters.json
