version: 2.1

orbs:
  continuation: circleci/continuation@0.2.0

parameters:
  setup-a:
    type: boolean
    default: false 
  run-workflow-b:
    type: boolean
    default: false
  run-workflow-c:
    type: boolean
    default: false
  run-workflow-d:
    type: boolean
    default: false
  manual-workflow-a:
    type: boolean
    default: false 
  manual-workflow-b:
    type: boolean
    default: false
  manual-workflow-c:
    type: boolean
    default: false
  manual-workflow-d:
    type: boolean
    default: false
jobs:
  buildjob:
    docker:
      - image: cimg/base:2022.01
    steps:
      - run: echo "test"   

workflows:
  workflow-a:
    when: 
      or: [<< pipeline.parameters.setuo-a >>, << pipeline.parameters.manual-workflow-a >>]
    jobs:
      - buildjob
  workflow-b:
    when:
      or: [<< pipeline.parameters.run-workflow-b >>, << pipeline.parameters.manual-workflow-b >>]
    jobs:
      - buildjob
  workflow-c:
    when:
      or: [<< pipeline.parameters.run-workflow-c >>, << pipeline.parameters.manual-workflow-c >>]
    jobs:
      - buildjob
  workflow-d:
    when:
      or: [<< pipeline.parameters.run-workflow-d >>, << pipeline.parameters.manual-workflow-d >>]
    jobs:
      - buildjob
