version: 2.1

parameters:
  setup-b:
    type: boolean
    default: false
  run-workflow-b:
    type: boolean
    default: false
  manual-workflow-b:
    type: boolean
    default: false
    
jobs:
  buildjob:
    docker:
      - image: cimg/base:2022.01
    steps:
      - run: echo "test"

workflows:
  workflow-b:
    when:
      or: [<< pipeline.parameters.run-workflow-b >>, << pipeline.parameters.manual-workflow-b >>]
    jobs:
      - buildjob
