version: 2.1

parameters:
  run-workflow-c:
    type: boolean
    default: false
  manual-workflow-c:
    type: boolean
    default: false 
  run-workflow-d:
    type: boolean
    default: false
  manual-workflow-d:
    type: boolean
    default: false 
    
jobs:
  buildjob:
    docker:
      - image: cimg/base:2022.01
    steps:
      - run: echo "test"

workflows:
  workflow-c:
    when:
      or: [<< pipeline.parameters.run-workflow-c >>, << pipeline.parameters.manual-workflow-c >>]
    jobs:
      - buildjob
  workflow-d:
    when:
      or: [<< pipeline.parameters.run-workflow-d >>, << pipeline.parameters.manual-workflow-d >>]
    jobs:
      - buildjob
