version: 2.1

parameters:
  setup-a:
    type: boolean
    default: false 
  manual-workflow-a:
    type: boolean
    default: false 
    
jobs:
  buildjob:
    docker:
      - image: cimg/base:2022.01
    steps:
      - run: echo "test"

workflows:
  workflow-a:
    when: 
      or: [<< pipeline.parameters.setup-a >>, << pipeline.parameters.manual-workflow-a >>]
    jobs:
      - buildjob
